version: '3.8'

services:
  # Telegram Bot API service
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: "${TELEGRAM_API_ID}"
      TELEGRAM_API_HASH: "${TELEGRAM_API_HASH}"
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"
  
  # Bot service
  bot:
    build: ./bot
    environment:
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres"
    depends_on:
      - telegram-bot-api
      - db

  # PostgreSQL service
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  telegram-bot-api-data:
  pgdata:
